language: node_js
node_js: 11.13.0
sudo: false

install:
    - npm install

services:
    - postgresql

before_script:
    - psql -c 'create database travisdb;' -U postgres
script:
    - npm run prebuild
    - npm run test
