language: node_js
node_js: 11.13.0
sudo: false

install:
    - npm install

services:
    - postgresql
env:
    - DATABASE_URL=postgres://postgres@localhost:5432/travisdb
before_script:
    - psql -c 'create database travisdb;' -U postgres
script:
    - npm run prebuild
    - npm run test
